<a href="https://colab.research.google.com/github/sg758253/AI/blob/main/numpy/Copy_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [ ]:
print(arr1)

[1 2 3 4]


In [ ]:
type(arr1)


numpy.ndarray

In [ ]:
arr1.ndim

1

In [ ]:
arr2 = np.array([[1,2],[3,4],[5,6]])

In [ ]:
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
type(arr2)

numpy.ndarray

In [ ]:
arr2.ndim

2

In [ ]:
arr2.size

6

In [ ]:
arr2.shape

(3, 2)

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
mx2 = np.ones((3,4))
mx2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
mx2 = np.ones((3,4),dtype=int)
print(mx2)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
mx2 = np.zeros((3,4),dtype=int)
print(mx2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
mx2 = np.zeros((3,4),dtype=bool)
print(mx2)

[[False False False False]
 [False False False False]
 [False False False False]]


In [ ]:
mx2 = np.zeros((3,4),dtype=str)
print(mx2)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [ ]:
en_str=''
print(bool(en_str))

False


In [ ]:
b=False
print(str(b))

False


In [ ]:
em_mx= np.empty((3,4))
print(em_mx)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
em_mx= np.empty((3,3))
print(em_mx)

[[4.65956748e-310 3.60739284e-313 1.38338381e-322]
 [4.65956748e-310 0.00000000e+000 0.00000000e+000]
 [4.94065646e-323 0.00000000e+000 0.00000000e+000]]


In [ ]:
em_mx= np.empty((4,3))
print(em_mx)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#np.arrange(start,end,steps)

In [ ]:
arr1 = np.arange(1,13,1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# linspace

In [ ]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

#Reshape

In [ ]:
#error
arr1.reshape(3,5)

ValueError: ignored

In [ ]:
#error
arr1.reshape(3,2)

ValueError: ignored

In [ ]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr1.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [ ]:
arr2d = np.arange(1,13).reshape(2,6)
print(arr2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


#ravel

In [ ]:
arr2d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#flatten

In [ ]:
arr2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Transpose

In [ ]:
arr2d.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [ ]:
arr2d.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [ ]:
arr1= np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2= np.arange(1,10).reshape(3,3)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr1+arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.add(arr1,arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
arr1-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.subtract(arr1,arr2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr1/arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.divide(arr1,arr2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
np.multiply(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

#Matrix production

In [ ]:
arr1@arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
arr1.dot(arr2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
arr1.max()

9

In [ ]:
arr1.argmax()

8

In [ ]:
#column = axis 0 
arr1.max(axis=0)

array([7, 8, 9])

In [ ]:
#row = axis 1
arr1.max(axis=1)

array([3, 6, 9])

In [ ]:
arr1.min()

1

In [ ]:
arr1.argmin()

0

In [ ]:
arr1.min(axis=0)

array([1, 2, 3])

In [ ]:
arr1.max(axis=1)

array([3, 6, 9])

In [ ]:
np.sum(arr1)

45

In [ ]:
np.sum(arr1,axis=0)

array([12, 15, 18])

In [ ]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [ ]:
np.mean(arr1)

5.0

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
np.std(arr1)

2.581988897471611

In [ ]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [ ]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

In [ ]:
mx = np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
mx[0,0]

1

In [ ]:
mx[0,0].ndim

0

In [ ]:
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
mx[0].ndim

1

In [ ]:
mx[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
mx[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [ ]:
mx[:,0:1].ndim

2

In [ ]:
mx[1:4,1:]

array([[12, 13, 14, 15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27, 28, 29, 30],
       [32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [ ]:
mx[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [ ]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
mx[:,1:2]

array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [ ]:
mx[::]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
mx[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
mx.itemsize

8

In [ ]:
mx.dtype

dtype('int64')

In [ ]:
64/8

8.0

In [ ]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
arr2 = np.arange(17,33).reshape(4,4)
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
list1 = [1,2,3]
list2 = [4,5,6]
list1+list2

[1, 2, 3, 4, 5, 6]

In [ ]:
arr1+arr2

array([[18, 20, 22, 24],
       [26, 28, 30, 32],
       [34, 36, 38, 40],
       [42, 44, 46, 48]])

In [ ]:
np.concatenate((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [ ]:
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print(arr2)

[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [ ]:
np.concatenate((arr1,arr2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [ ]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [ ]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [ ]:
np.hstack((arr1,arr2,arr1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [ ]:
list1 = np.split(arr1,2)
print(list1)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]


In [ ]:
type(list1)

list

In [ ]:
list1[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
type(list1[0])

numpy.ndarray

In [ ]:
list2 = np.split(arr1,2,axis=1)
list2

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]), array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [ ]:
d1 = np.array([4,7,1,3,9])

In [ ]:
np.split(d1,[1,3])

[array([4]), array([7, 1]), array([3, 9])]